### ISSUE TITLE
Sometimes it just stops working...

### ISSUE THREAD

**Issue by sfinktah** [eset/ipyida#39]
Hi, this has been a problem for me ever since I first tried your lovely plugin back in 6.8.

I am now using 7.5 and I still suffer the same issue.

Something will happen, and when I next try to open the IPython Console window, all I get are 

    ...

And if I type something like `1 + 2` into IDA's output console, `3` will appear in the IPython Console window.

However I have just now managed to get a page of error output, after hitting ^D and ^C and ^Z and anything I could think of.

As I suspected:

```
Traceback (most recent call last):
  File "C:\Users\sfink\AppData\Local\Programs\Python\Python37\lib\site-packages\qtconsole\console_widget.py", line 427, in eventFilter
    return self._event_filter_console_keypress(event)
  File "C:\Users\sfink\AppData\Local\Programs\Python\Python37\lib\site-packages\qtconsole\frontend_widget.py", line 355, in _event_filter_console_keypress
    self.request_interrupt_kernel()
  File "C:\Users\sfink\AppData\Local\Programs\Python\Python37\lib\site-packages\qtconsole\frontend_widget.py", line 338, in request_interrupt_kernel
    self.interrupt_kernel()
  File "C:\Users\sfink\AppData\Local\Programs\Python\Python37\lib\site-packages\qtconsole\frontend_widget.py", line 629, in interrupt_kernel
    self.kernel_manager.interrupt_kernel()
  File "C:\Users\sfink\AppData\Local\Programs\Python\Python37\lib\site-packages\jupyter_client\manager.py", line 511, in interrupt_kernel
    raise RuntimeError("Cannot interrupt kernel. No kernel is running!")
RuntimeError: Cannot interrupt kernel. No kernel is running!
Traceback (most recent call last):
  File "C:\Users\sfink\AppData\Local\Programs\Python\Python37\lib\site-packages\qtconsole\console_widget.py", line 427, in eventFilter
    return self._event_filter_console_keypress(event)
  File "C:\Users\sfink\AppData\Local\Programs\Python\Python37\lib\site-packages\qtconsole\frontend_widget.py", line 355, in _event_filter_console_keypress
    self.request_interrupt_kernel()
  File "C:\Users\sfink\AppData\Local\Programs\Python\Python37\lib\site-packages\qtconsole\frontend_widget.py", line 338, in request_interrupt_kernel
    self.interrupt_kernel()
  File "C:\Users\sfink\AppData\Local\Programs\Python\Python37\lib\site-packages\qtconsole\frontend_widget.py", line 629, in interrupt_kernel
    self.kernel_manager.interrupt_kernel()
  File "C:\Users\sfink\AppData\Local\Programs\Python\Python37\lib\site-packages\jupyter_client\manager.py", line 511, in interrupt_kernel
    raise RuntimeError("Cannot interrupt kernel. No kernel is running!")
RuntimeError: Cannot interrupt kernel. No kernel is running!
```

How to restart the kernel?

**Comment by marc-etienne** [comment]
Hi @sfinktah,

I've never experienced this issue before. Can you tell me which version of the dependencies you have installed by running `import pip._internal; pip._internal.main(["freeze"])` in IDA's console?

**Comment by sfinktah** [comment]
Sure, thanks for the useful commands too.  I spent an hour last week searching for how to use PIP directly from IDA and found nothing but statements it wasn't possible.

This use to happen years ago with Python 2.7, though back then I seem to recall it was related to closing the IPython window.

This is the output from running the command from one of the IDAs which still has a working IPython.  (I have 3 IDAs open, which is SOP for me and could be a factor -- though the other two have had no issues).

The output is the same from the broken IDA.

The only other plugins I'm only running are HexRaysPyTools.py and xray, as I've only migrated to the Python 3 ecosphere recently.   If you happen to know to reload python plugins (the annoying kind that complain vociferously if they aren't called from `PLUGIN_ENTY()`, that would be a handy thing to know.  I write lots of IDAPython code, but haven't written any `plugins/`


```
Jupyter QtConsole 5.0.2
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.20.0 -- An enhanced Interactive Python. Type '?' for help.
```

```
argon2-cffi==20.1.0
async-generator==1.10
attrs==20.3.0
backcall==0.2.0
bleach==3.3.0
certifi==2020.12.5
cffi==1.14.5
chardet==4.0.0
colorama==0.4.4
decorator==4.4.2
defusedxml==0.6.0
distorm3==3.5.1
entrypoints==0.3
fuzzywuzzy==0.18.0
idna==2.10
img2pdf==0.3.3
importlib-metadata==3.4.0
ipyida==1.5
ipykernel==4.10.1
ipython==7.20.0
ipython-genutils==0.2.0
ipywidgets==7.6.3
jedi==0.18.0
Jinja2==2.11.3
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.1.11
jupyter-console==6.2.0
jupyter-core==4.7.1
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.0
keystone-engine==0.9.2
MarkupSafe==1.1.1
matrix-client==0.3.2
matrix-dl==0.0.1
mistune==0.8.4
nbclient==0.5.2
nbconvert==6.0.7
nbformat==5.1.2
nest-asyncio==1.5.1
notebook==6.2.0
packaging==20.9
pandocfilters==1.4.3
parso==0.8.1
pickleshare==0.7.5
Pillow==7.0.0
prometheus-client==0.9.0
prompt-toolkit==3.0.16
psutil==5.7.3
pybind11==2.6.0
pycparser==2.20
Pygments==2.4.2
pyparsing==2.4.7
PyQt5==5.15.2
PyQt5-sip==12.8.1
pyrsistent==0.17.3
python-dateutil==2.8.1
python-Levenshtein==0.12.2
pywin32==300
pywinpty==0.5.7
pyzmq==22.0.2
qtconsole==5.0.2
QtPy==1.9.0
requests==2.25.1
Send2Trash==1.5.0
six==1.15.0
terminado==0.9.2
testpath==0.4.4
tornado==6.1
traitlets==5.0.5
typing-extensions==3.7.4.3
underscore.py==0.1.6
unicorn==1.0.2
urllib3==1.26.2
wcwidth==0.2.5
webencodings==0.5.1
widgetsnbextension==3.5.1
xmltodict==0.12.0
zipp==3.4.0
zmq==0.0.0
```

**Comment by sfinktah** [comment]
I should add that I frequently manage to induce `RuntimeError`s, which may be a factor.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 9, in find_lame_memcpys
  File "e:/git/ida\slowtrace2.py", line 690, in retrace
    #  LabelAddressPlus(ea, slowtrace2.startFnName, force=1)
  File "e:/git/ida\slowtrace2.py", line 3326, in slowtrace2
  File "C:\Program Files\IDA 7.5\python\3\idc_bc695.py", line 240, in AppendFchunk
    def AppendFchunk(funcea, ea1, ea2): return append_func_tail(funcea, ea1, ea2)
  File "C:\Program Files\IDA 7.5\python\3\idc.py", line 4217, in append_func_tail
    return ida_funcs.append_func_tail(func, ea1, ea2)
  File "C:\Program Files\IDA 7.5\python\3\ida_funcs.py", line 1245, in append_func_tail
    return _ida_funcs.append_func_tail(*args)
RuntimeError: Internal error 1543 occurred when running a script. Either
  - the script misused the IDA API, or
  - there is a logic error in IDA
Please check the script first.
If it appears correct, send a bug report to <support@hex-rays.com>.
In any case we strongly recommend you to restart IDA as soon as possible.
```

**Comment by sfinktah** [comment]
Closing as apparently I didn't have the latest version installed.
