### ISSUE TITLE
IDA 6.8 Win7x64 Installer Error

### ISSUE THREAD

**Issue by tylerhalfpop** [eset/ipyida#4]
Python>import urllib2; exec urllib2.urlopen('https://github.com/eset/ipyida/raw/stable/install_from_ida.py').read()
[+] Using already installed pip (version 7.0.1)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 52, in <module>
  File "C:\Python27\lib\site-packages\pip\__init__.py", line 217, in main
    return command.main(cmd_args)
  File "C:\Python27\lib\site-packages\pip\basecommand.py", line 185, in main
    for name in ["pip._vendor", "distlib", "requests", "urllib3"]
  File "C:\Python27\Lib\logging\config.py", line 803, in dictConfig
    dictConfigClass(config).configure()
  File "C:\Python27\Lib\logging\config.py", line 585, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler 'console': IDAPythonStdOut instance has no attribute 'closed'

**Comment by marc-etienne** [comment]
Hi!

Thanks for reporting the issue.

It seems that pip 7.0.1 doesn't like sys.stdout to be set to a non-file object. I tried to fix it in the master branch.

Can try the following?

````
import urllib2; exec urllib2.urlopen('https://github.com/eset/ipyida/raw/master/install_from_ida.py').read()
````

**Comment by tylerhalfpop** [comment]
Fix worked great.  Love this :-)  Thank you!

**Comment by marc-etienne** [comment]
Awesome!
Cheers!
M-E
