### ISSUE TITLE
Installation fails with Python 3.9.7 on Windows

### ISSUE THREAD

**Issue by ioncodes** [eset/ipyida#45]
Installation fails with Python 3.9.7 in IDA Pro 7.6 on Windows:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 95, in <module>
  File "<string>", line 92, in pip_install
  File "C:\Users\luca\AppData\Local\Programs\Python\Python39\Lib\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "<string>", line 49, in temp_file_as_stdout
  File "C:\Users\luca\AppData\Local\Programs\Python\Python39\lib\site-packages\ipyida\kernel.py", line 73, in write
    super(self.__class__, self).write(string)
  File "C:\Users\luca\AppData\Local\Programs\Python\Python39\lib\site-packages\ipykernel\iostream.py", line 511, in write
    raise TypeError(
TypeError: write() argument must be str, not <class 'bytes'>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 95, in <module>
  File "<string>", line 92, in pip_install
  File "C:\Users\luca\AppData\Local\Programs\Python\Python39\Lib\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "<string>", line 49, in temp_file_as_stdout
  File "C:\Users\luca\AppData\Local\Programs\Python\Python39\lib\site-packages\ipyida\kernel.py", line 73, in write
    super(self.__class__, self).write(string)
  File "C:\Users\luca\AppData\Local\Programs\Python\Python39\lib\site-packages\ipykernel\iostream.py", line 511, in write
    raise TypeError(
TypeError: write() argument must be str, not <class 'bytes'>
```

```
Python>print(sys.version_info)
sys.version_info(major=3, minor=9, micro=7, releaselevel='final', serial=0)
```

Installing it manually yields this error:

```
ipyida_plugin_stub.py: PLUGIN_ENTRY was not defined or the class name 'IPyIDAPlugIn' was already used in 'ipyida.py'
```

**Comment by Flyour** [comment]
![image](https://user-images.githubusercontent.com/30471484/135955716-2fec1382-e061-4acb-a678-afad7c379aa9.png)

Just add a line to decode bytes in ipyida\kernel.py
