### ISSUE TITLE
NotImplementedError on win32

### ISSUE THREAD

**Issue by Cirn09** [eset/ipyida#46]
```
C:\Portable Program\IDA Pro 7.5\plugins\ipyida_plugin_stub.py: 
Traceback (most recent call last):
  File "C:\Portable Program\IDA Pro 7.5\python\3\ida_idaapi.py", line 616, in IDAPython_ExecScript
    exec(code, g)
  File "C:/Portable Program/IDA Pro 7.5/plugins/ipyida_plugin_stub.py", line 11, in <module>
    from ipyida.ida_plugin import PLUGIN_ENTRY, IPyIDAPlugIn
  File "C:\Portable Program\Python38\lib\site-packages\ipyida\ida_plugin.py", line 62, in <module>
    _kernel.start()
  File "C:\Portable Program\Python38\lib\site-packages\ipyida\kernel.py", line 113, in start
    app.initialize()
  File "C:\Portable Program\Python38\lib\site-packages\traitlets\config\application.py", line 86, in inner
    return method(app, *args, **kwargs)
  File "C:\Portable Program\Python38\lib\site-packages\ipykernel\kernelapp.py", line 469, in initialize
    self.init_sockets()
  File "C:\Portable Program\Python38\lib\site-packages\ipykernel\kernelapp.py", line 260, in init_sockets
    self.init_iopub(context)
  File "C:\Portable Program\Python38\lib\site-packages\ipykernel\kernelapp.py", line 268, in init_iopub
    self.iopub_thread = IOPubThread(self.iopub_socket, pipe=True)
  File "C:\Portable Program\Python38\lib\site-packages\ipykernel\iostream.py", line 68, in __init__
    self._setup_pipe_in()
  File "C:\Portable Program\Python38\lib\site-packages\ipykernel\iostream.py", line 141, in _setup_pipe_in
    self._pipe_in = ZMQStream(pipe_in, self.io_loop)
  File "C:\Portable Program\Python38\lib\site-packages\zmq\eventloop\zmqstream.py", line 127, in __init__
    self._init_io_state()
  File "C:\Portable Program\Python38\lib\site-packages\zmq\eventloop\zmqstream.py", line 552, in _init_io_state
    self.io_loop.add_handler(self.socket, self._handle_events, self.io_loop.READ)
  File "C:\Portable Program\Python38\lib\site-packages\tornado\platform\asyncio.py", line 100, in add_handler
    self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "C:\Portable Program\Python38\Lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError
```

easy to fix, just add little code to `ipyida_plugin_stub.py`:

```
import sys
import asyncio
if sys.platform == 'win32':
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
```

**Comment by Cirn09** [comment]
> Thanks for bringing this problem back to my attention.
> 
> I checked IPyKernel code and it seems this change was already introduced in v5.1.4: see [ipython/ipykernel@f40d74a](https://github.com/ipython/ipykernel/commit/f40d74afe52c4f45749860d293b6f55ac7e0e7d4)
> 
> Can you check what version of IPyKernel version you have installed? Based on the line number of `self.init_sockets()` in you stack trace, I think you have `<= 5.1.1`.
> 
> Can you try updating the `ipykernel` package and try IPyIDA without the patch?
> 
> Cheers!

Cheers! This problem disappeared after I upgraded `ipykernel`.
In order to avoid the same problem from happening again in others, I suggest to modify https://github.com/eset/ipyida/blob/0fee04f327/setup.py#L32 to `ipykernel>=5.1.4'`
