### ISSUE TITLE
exception when run in idat

### ISSUE THREAD

**Issue by Cirn09** [eset/ipyida#55]
```
Exception ignored in: <function BaseEventLoop.__del__ at 0x000002DD8152CE50>
Traceback (most recent call last):
  File "C:\Portable Program\Python310\Lib\asyncio\base_events.py", line 684, in __del__
    if not self.is_closed():
  File "C:\Portable Program\Python310\Lib\asyncio\base_events.py", line 681, in is_closed
    return self._closed
AttributeError: 'QIOCPEventLoop' object has no attribute '_closed'
C:\Users\Cirn09\AppData\Roaming\Hex-Rays\IDA Pro\plugins\ipyida_plugin_stub.py: No QApplication has been instantiated
Traceback (most recent call last):
  File "C:\Portable Program\IDA Pro 7.7\python\3\ida_idaapi.py", line 580, in IDAPython_ExecScript
    exec(code, g)
  File "C:/Users/Cirn09/AppData/Roaming/Hex-Rays/IDA Pro/plugins/ipyida_plugin_stub.py", line 11, in <module>
    from ipyida.ida_plugin import PLUGIN_ENTRY, IPyIDAPlugIn
  File "C:\Portable Program\Python310\lib\site-packages\ipyida\ida_plugin.py", line 59, in <module>
    _setup_asyncio_event_loop()
  File "C:\Portable Program\Python310\lib\site-packages\ipyida\ida_plugin.py", line 55, in _setup_asyncio_event_loop
    loop = qasync.QEventLoop(qapp, already_running=True)
  File "C:\Portable Program\Python310\lib\site-packages\qasync\__init__.py", line 336, in __init__
    assert self.__app is not None, "No QApplication has been instantiated"
AssertionError: No QApplication has been instantiated
```

idat is running in terminal without GUI.
We should find a way to check is ida or idat!

**Comment by marc-etienne** [comment]
Hey @Cirn09!

Thanks for reporting. This issue has already be fixed in ff0f5552 and the change will be part of the next release which should be in the next few weeks,

Cheers!
M-E
