### ISSUE TITLE
Installation uses deprecated python APIs and fails on Archlinux

### ISSUE THREAD

**Issue by Alexeyan** [eset/ipyida#67]
Hi.

When trying to install it in Ida it fails with 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 16, in <module>
  File "/home/foo/.local/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2191, in <module>
    register_finder(pkgutil.ImpImporter, find_on_path)
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
```

Python 3.12 deprecated this installation method afaik.

**Comment by marc-etienne** [comment]
You are right, the script uses two deprecated functions from `pkg_resources`:

- https://github.com/eset/ipyida/blob/100c655f1a951551a5aeeb4157adac6ed9bbc907/install_from_ida.py#L153
- https://github.com/eset/ipyida/blob/100c655f1a951551a5aeeb4157adac6ed9bbc907/install_from_ida.py#L160

For the first one I found this guide to use `importlib` instead: https://importlib-resources.readthedocs.io/en/latest/migration.html.

I'll try to update the script.

**Comment by marc-etienne** [comment]
BTW, I'd wait before updating to Python 3.12 in IDA, there are other issues in IDAPython which make IDA crash (see #65). Maybe this is fixed in 9.0, but I can't confirm.

**Comment by marc-etienne** [comment]
FYI, the installation script has now been updated to support Python 3.12 and later, so I'll close this. From my testing, IDA (and IPyIDA) also with recent versions of Python.
